### ISSUE TITLE
Compton "On the potential deprecation of --glx-fshader-win"

### ISSUE THREAD

**Issue by JackKenney** [vn971/linux-color-inversion#7]
Just bringing this to your attention:
https://github.com/chjj/compton/issues/542

**Comment by vn971** [comment]
Yeah, thanks, I'm aware of the issue. The problem is that it is raised in the wrong github repo. The change itself is from the fork, and there, it is already raised as well: https://github.com/yshui/picom/issues/108

Furthermore, the deprecation was removed, and the "API" is now considered stable: https://github.com/yshui/picom/issues/108#issuecomment-547025274

so no reason to worry about.
